package org.zucc.web.entity;

import java.io.Serializable;
import java.util.Date;

public class Admin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPwd
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String adminpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admincreateTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date admincreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAdminid(Long adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPwd
     *
     * @return the value of admin.adminPwd
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getAdminpwd() {
        return adminpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPwd
     *
     * @param adminpwd the value for admin.adminPwd
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAdminpwd(String adminpwd) {
        this.adminpwd = adminpwd == null ? null : adminpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admincreateTime
     *
     * @return the value of admin.admincreateTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getAdmincreatetime() {
        return admincreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admincreateTime
     *
     * @param admincreatetime the value for admin.admincreateTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAdmincreatetime(Date admincreatetime) {
        this.admincreatetime = admincreatetime;
    }
}