package org.zucc.web.entity;

import java.io.Serializable;
import java.util.Date;

public class IAnnouncement implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_announcement.announcement_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long announcementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_announcement.announcement_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String announcementImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_announcement.announcement_url
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String announcementUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_announcement.announcement_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String announcementDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_announcement.announcement_createTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date announcementCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_announcement.announcement_admin_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long announcementAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_announcement
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_announcement.announcement_id
     *
     * @return the value of i_announcement.announcement_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_announcement.announcement_id
     *
     * @param announcementId the value for i_announcement.announcement_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAnnouncementId(Long announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_announcement.announcement_image
     *
     * @return the value of i_announcement.announcement_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getAnnouncementImage() {
        return announcementImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_announcement.announcement_image
     *
     * @param announcementImage the value for i_announcement.announcement_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAnnouncementImage(String announcementImage) {
        this.announcementImage = announcementImage == null ? null : announcementImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_announcement.announcement_url
     *
     * @return the value of i_announcement.announcement_url
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getAnnouncementUrl() {
        return announcementUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_announcement.announcement_url
     *
     * @param announcementUrl the value for i_announcement.announcement_url
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAnnouncementUrl(String announcementUrl) {
        this.announcementUrl = announcementUrl == null ? null : announcementUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_announcement.announcement_description
     *
     * @return the value of i_announcement.announcement_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getAnnouncementDescription() {
        return announcementDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_announcement.announcement_description
     *
     * @param announcementDescription the value for i_announcement.announcement_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAnnouncementDescription(String announcementDescription) {
        this.announcementDescription = announcementDescription == null ? null : announcementDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_announcement.announcement_createTime
     *
     * @return the value of i_announcement.announcement_createTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getAnnouncementCreatetime() {
        return announcementCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_announcement.announcement_createTime
     *
     * @param announcementCreatetime the value for i_announcement.announcement_createTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAnnouncementCreatetime(Date announcementCreatetime) {
        this.announcementCreatetime = announcementCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_announcement.announcement_admin_id
     *
     * @return the value of i_announcement.announcement_admin_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getAnnouncementAdminId() {
        return announcementAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_announcement.announcement_admin_id
     *
     * @param announcementAdminId the value for i_announcement.announcement_admin_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAnnouncementAdminId(Long announcementAdminId) {
        this.announcementAdminId = announcementAdminId;
    }
}