package org.zucc.web.entity;

import java.io.Serializable;

public class ICard implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_card.cardId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_card.cardNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Integer cardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_card.account_aid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long accountAid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_card
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_card.cardId
     *
     * @return the value of i_card.cardId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_card.cardId
     *
     * @param cardid the value for i_card.cardId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCardid(Long cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_card.cardNum
     *
     * @return the value of i_card.cardNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Integer getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_card.cardNum
     *
     * @param cardnum the value for i_card.cardNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCardnum(Integer cardnum) {
        this.cardnum = cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_card.account_aid
     *
     * @return the value of i_card.account_aid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getAccountAid() {
        return accountAid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_card.account_aid
     *
     * @param accountAid the value for i_card.account_aid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setAccountAid(Long accountAid) {
        this.accountAid = accountAid;
    }
}