package org.zucc.web.entity;

import java.io.Serializable;

public class IClassroom implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_classroom.classroom_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long classroomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_classroom.classroom_address
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String classroomAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_classroom.classroom_capacity
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Integer classroomCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_classroom
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_classroom.classroom_id
     *
     * @return the value of i_classroom.classroom_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getClassroomId() {
        return classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_classroom.classroom_id
     *
     * @param classroomId the value for i_classroom.classroom_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setClassroomId(Long classroomId) {
        this.classroomId = classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_classroom.classroom_address
     *
     * @return the value of i_classroom.classroom_address
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getClassroomAddress() {
        return classroomAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_classroom.classroom_address
     *
     * @param classroomAddress the value for i_classroom.classroom_address
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setClassroomAddress(String classroomAddress) {
        this.classroomAddress = classroomAddress == null ? null : classroomAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_classroom.classroom_capacity
     *
     * @return the value of i_classroom.classroom_capacity
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Integer getClassroomCapacity() {
        return classroomCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_classroom.classroom_capacity
     *
     * @param classroomCapacity the value for i_classroom.classroom_capacity
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setClassroomCapacity(Integer classroomCapacity) {
        this.classroomCapacity = classroomCapacity;
    }
}