package org.zucc.web.entity;

import java.io.Serializable;

public class IColletion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_colletion.collectionId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long collectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_colletion.colletion_userid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long colletionUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_colletion.colletion_course_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long colletionCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_colletion.collectionId
     *
     * @return the value of i_colletion.collectionId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getCollectionid() {
        return collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_colletion.collectionId
     *
     * @param collectionid the value for i_colletion.collectionId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCollectionid(Long collectionid) {
        this.collectionid = collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_colletion.colletion_userid
     *
     * @return the value of i_colletion.colletion_userid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getColletionUserid() {
        return colletionUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_colletion.colletion_userid
     *
     * @param colletionUserid the value for i_colletion.colletion_userid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setColletionUserid(Long colletionUserid) {
        this.colletionUserid = colletionUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_colletion.colletion_course_id
     *
     * @return the value of i_colletion.colletion_course_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getColletionCourseId() {
        return colletionCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_colletion.colletion_course_id
     *
     * @param colletionCourseId the value for i_colletion.colletion_course_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setColletionCourseId(Long colletionCourseId) {
        this.colletionCourseId = colletionCourseId;
    }
}