package org.zucc.web.entity;

import java.io.Serializable;
import java.util.Date;

public class IComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_comment.commentId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_comment.comment_courseId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long commentCourseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_comment.comment_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long commentUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_comment.comment_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String commentDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_comment.comment_createTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date commentCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_comment.comment_course_score
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Integer commentCourseScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_comment.commentId
     *
     * @return the value of i_comment.commentId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_comment.commentId
     *
     * @param commentid the value for i_comment.commentId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCommentid(Long commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_comment.comment_courseId
     *
     * @return the value of i_comment.comment_courseId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getCommentCourseid() {
        return commentCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_comment.comment_courseId
     *
     * @param commentCourseid the value for i_comment.comment_courseId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCommentCourseid(Long commentCourseid) {
        this.commentCourseid = commentCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_comment.comment_userId
     *
     * @return the value of i_comment.comment_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getCommentUserid() {
        return commentUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_comment.comment_userId
     *
     * @param commentUserid the value for i_comment.comment_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCommentUserid(Long commentUserid) {
        this.commentUserid = commentUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_comment.comment_description
     *
     * @return the value of i_comment.comment_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getCommentDescription() {
        return commentDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_comment.comment_description
     *
     * @param commentDescription the value for i_comment.comment_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCommentDescription(String commentDescription) {
        this.commentDescription = commentDescription == null ? null : commentDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_comment.comment_createTime
     *
     * @return the value of i_comment.comment_createTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getCommentCreatetime() {
        return commentCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_comment.comment_createTime
     *
     * @param commentCreatetime the value for i_comment.comment_createTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCommentCreatetime(Date commentCreatetime) {
        this.commentCreatetime = commentCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_comment.comment_course_score
     *
     * @return the value of i_comment.comment_course_score
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Integer getCommentCourseScore() {
        return commentCourseScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_comment.comment_course_score
     *
     * @param commentCourseScore the value for i_comment.comment_course_score
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCommentCourseScore(Integer commentCourseScore) {
        this.commentCourseScore = commentCourseScore;
    }
}