package org.zucc.web.entity;

import java.io.Serializable;
import java.util.Date;

public class ICoupon implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_coupon.couponId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long couponid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_coupon.couponMoney
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Double couponmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_coupon.couponEndDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date couponenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_coupon.coupon_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long couponUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_coupon.couponId
     *
     * @return the value of i_coupon.couponId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getCouponid() {
        return couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_coupon.couponId
     *
     * @param couponid the value for i_coupon.couponId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCouponid(Long couponid) {
        this.couponid = couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_coupon.couponMoney
     *
     * @return the value of i_coupon.couponMoney
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Double getCouponmoney() {
        return couponmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_coupon.couponMoney
     *
     * @param couponmoney the value for i_coupon.couponMoney
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCouponmoney(Double couponmoney) {
        this.couponmoney = couponmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_coupon.couponEndDate
     *
     * @return the value of i_coupon.couponEndDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getCouponenddate() {
        return couponenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_coupon.couponEndDate
     *
     * @param couponenddate the value for i_coupon.couponEndDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCouponenddate(Date couponenddate) {
        this.couponenddate = couponenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_coupon.coupon_userId
     *
     * @return the value of i_coupon.coupon_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getCouponUserid() {
        return couponUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_coupon.coupon_userId
     *
     * @param couponUserid the value for i_coupon.coupon_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCouponUserid(Long couponUserid) {
        this.couponUserid = couponUserid;
    }
}