package org.zucc.web.entity;

import java.io.Serializable;
import java.util.Date;

public class ICourse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_cid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long cCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_cname
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String cCname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_price
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Double cPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_address
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String cAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_collection
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Integer cCollection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_teacherId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long cTeacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String cDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_simple_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String cSimpleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_courseMinNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Integer cCourseminnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_courseMaxNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Integer cCoursemaxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_courseNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Integer cCoursenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_startTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date cStarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_endTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date cEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_thumbnail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String cThumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_imageOne
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String cImageone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_imageTwo
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String cImagetwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_imageThree
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String cImagethree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long cUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_classroom_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long cClassroomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_coursetype_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long cCoursetypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_classStartDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date cClassstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_classEndDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date cClassenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_classStartTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date cClassstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_classEndTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date cClassendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_recommend
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Boolean cRecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course.c_schedule
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Boolean cSchedule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_course
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_cid
     *
     * @return the value of i_course.c_cid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getcCid() {
        return cCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_cid
     *
     * @param cCid the value for i_course.c_cid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcCid(Long cCid) {
        this.cCid = cCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_cname
     *
     * @return the value of i_course.c_cname
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getcCname() {
        return cCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_cname
     *
     * @param cCname the value for i_course.c_cname
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcCname(String cCname) {
        this.cCname = cCname == null ? null : cCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_price
     *
     * @return the value of i_course.c_price
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Double getcPrice() {
        return cPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_price
     *
     * @param cPrice the value for i_course.c_price
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcPrice(Double cPrice) {
        this.cPrice = cPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_address
     *
     * @return the value of i_course.c_address
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_address
     *
     * @param cAddress the value for i_course.c_address
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress == null ? null : cAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_collection
     *
     * @return the value of i_course.c_collection
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Integer getcCollection() {
        return cCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_collection
     *
     * @param cCollection the value for i_course.c_collection
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcCollection(Integer cCollection) {
        this.cCollection = cCollection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_teacherId
     *
     * @return the value of i_course.c_teacherId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getcTeacherid() {
        return cTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_teacherId
     *
     * @param cTeacherid the value for i_course.c_teacherId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcTeacherid(Long cTeacherid) {
        this.cTeacherid = cTeacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_description
     *
     * @return the value of i_course.c_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getcDescription() {
        return cDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_description
     *
     * @param cDescription the value for i_course.c_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcDescription(String cDescription) {
        this.cDescription = cDescription == null ? null : cDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_simple_description
     *
     * @return the value of i_course.c_simple_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getcSimpleDescription() {
        return cSimpleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_simple_description
     *
     * @param cSimpleDescription the value for i_course.c_simple_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcSimpleDescription(String cSimpleDescription) {
        this.cSimpleDescription = cSimpleDescription == null ? null : cSimpleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_courseMinNum
     *
     * @return the value of i_course.c_courseMinNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Integer getcCourseminnum() {
        return cCourseminnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_courseMinNum
     *
     * @param cCourseminnum the value for i_course.c_courseMinNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcCourseminnum(Integer cCourseminnum) {
        this.cCourseminnum = cCourseminnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_courseMaxNum
     *
     * @return the value of i_course.c_courseMaxNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Integer getcCoursemaxnum() {
        return cCoursemaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_courseMaxNum
     *
     * @param cCoursemaxnum the value for i_course.c_courseMaxNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcCoursemaxnum(Integer cCoursemaxnum) {
        this.cCoursemaxnum = cCoursemaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_courseNum
     *
     * @return the value of i_course.c_courseNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Integer getcCoursenum() {
        return cCoursenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_courseNum
     *
     * @param cCoursenum the value for i_course.c_courseNum
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcCoursenum(Integer cCoursenum) {
        this.cCoursenum = cCoursenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_startTime
     *
     * @return the value of i_course.c_startTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getcStarttime() {
        return cStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_startTime
     *
     * @param cStarttime the value for i_course.c_startTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcStarttime(Date cStarttime) {
        this.cStarttime = cStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_endTime
     *
     * @return the value of i_course.c_endTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getcEndtime() {
        return cEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_endTime
     *
     * @param cEndtime the value for i_course.c_endTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcEndtime(Date cEndtime) {
        this.cEndtime = cEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_thumbnail
     *
     * @return the value of i_course.c_thumbnail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getcThumbnail() {
        return cThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_thumbnail
     *
     * @param cThumbnail the value for i_course.c_thumbnail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcThumbnail(String cThumbnail) {
        this.cThumbnail = cThumbnail == null ? null : cThumbnail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_imageOne
     *
     * @return the value of i_course.c_imageOne
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getcImageone() {
        return cImageone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_imageOne
     *
     * @param cImageone the value for i_course.c_imageOne
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcImageone(String cImageone) {
        this.cImageone = cImageone == null ? null : cImageone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_imageTwo
     *
     * @return the value of i_course.c_imageTwo
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getcImagetwo() {
        return cImagetwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_imageTwo
     *
     * @param cImagetwo the value for i_course.c_imageTwo
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcImagetwo(String cImagetwo) {
        this.cImagetwo = cImagetwo == null ? null : cImagetwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_imageThree
     *
     * @return the value of i_course.c_imageThree
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getcImagethree() {
        return cImagethree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_imageThree
     *
     * @param cImagethree the value for i_course.c_imageThree
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcImagethree(String cImagethree) {
        this.cImagethree = cImagethree == null ? null : cImagethree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_userId
     *
     * @return the value of i_course.c_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getcUserid() {
        return cUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_userId
     *
     * @param cUserid the value for i_course.c_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcUserid(Long cUserid) {
        this.cUserid = cUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_classroom_id
     *
     * @return the value of i_course.c_classroom_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getcClassroomId() {
        return cClassroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_classroom_id
     *
     * @param cClassroomId the value for i_course.c_classroom_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcClassroomId(Long cClassroomId) {
        this.cClassroomId = cClassroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_coursetype_id
     *
     * @return the value of i_course.c_coursetype_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getcCoursetypeId() {
        return cCoursetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_coursetype_id
     *
     * @param cCoursetypeId the value for i_course.c_coursetype_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcCoursetypeId(Long cCoursetypeId) {
        this.cCoursetypeId = cCoursetypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_classStartDate
     *
     * @return the value of i_course.c_classStartDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getcClassstartdate() {
        return cClassstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_classStartDate
     *
     * @param cClassstartdate the value for i_course.c_classStartDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcClassstartdate(Date cClassstartdate) {
        this.cClassstartdate = cClassstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_classEndDate
     *
     * @return the value of i_course.c_classEndDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getcClassenddate() {
        return cClassenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_classEndDate
     *
     * @param cClassenddate the value for i_course.c_classEndDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcClassenddate(Date cClassenddate) {
        this.cClassenddate = cClassenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_classStartTime
     *
     * @return the value of i_course.c_classStartTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getcClassstarttime() {
        return cClassstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_classStartTime
     *
     * @param cClassstarttime the value for i_course.c_classStartTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcClassstarttime(Date cClassstarttime) {
        this.cClassstarttime = cClassstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_classEndTime
     *
     * @return the value of i_course.c_classEndTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getcClassendtime() {
        return cClassendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_classEndTime
     *
     * @param cClassendtime the value for i_course.c_classEndTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcClassendtime(Date cClassendtime) {
        this.cClassendtime = cClassendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_recommend
     *
     * @return the value of i_course.c_recommend
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Boolean getcRecommend() {
        return cRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_recommend
     *
     * @param cRecommend the value for i_course.c_recommend
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcRecommend(Boolean cRecommend) {
        this.cRecommend = cRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course.c_schedule
     *
     * @return the value of i_course.c_schedule
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Boolean getcSchedule() {
        return cSchedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course.c_schedule
     *
     * @param cSchedule the value for i_course.c_schedule
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setcSchedule(Boolean cSchedule) {
        this.cSchedule = cSchedule;
    }
}