package org.zucc.web.entity;

import java.io.Serializable;

public class ICourseType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course_type.course_type_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long courseTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_course_type.course_type_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String courseTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course_type.course_type_id
     *
     * @return the value of i_course_type.course_type_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getCourseTypeId() {
        return courseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course_type.course_type_id
     *
     * @param courseTypeId the value for i_course_type.course_type_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCourseTypeId(Long courseTypeId) {
        this.courseTypeId = courseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_course_type.course_type_name
     *
     * @return the value of i_course_type.course_type_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getCourseTypeName() {
        return courseTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_course_type.course_type_name
     *
     * @param courseTypeName the value for i_course_type.course_type_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setCourseTypeName(String courseTypeName) {
        this.courseTypeName = courseTypeName == null ? null : courseTypeName.trim();
    }
}