package org.zucc.web.entity;

import java.io.Serializable;

public class IEnroll implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long enrollId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_courseId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long enrollCourseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long enrollUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_question
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String enrollQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_phone
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String enrollPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String enrollName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String enrollCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_position
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String enrollPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_email
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String enrollEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_money
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Double enrollMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_enroll.enroll_pay_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Boolean enrollPayState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_enroll
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_id
     *
     * @return the value of i_enroll.enroll_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getEnrollId() {
        return enrollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_id
     *
     * @param enrollId the value for i_enroll.enroll_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollId(Long enrollId) {
        this.enrollId = enrollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_courseId
     *
     * @return the value of i_enroll.enroll_courseId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getEnrollCourseid() {
        return enrollCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_courseId
     *
     * @param enrollCourseid the value for i_enroll.enroll_courseId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollCourseid(Long enrollCourseid) {
        this.enrollCourseid = enrollCourseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_userId
     *
     * @return the value of i_enroll.enroll_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getEnrollUserid() {
        return enrollUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_userId
     *
     * @param enrollUserid the value for i_enroll.enroll_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollUserid(Long enrollUserid) {
        this.enrollUserid = enrollUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_question
     *
     * @return the value of i_enroll.enroll_question
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getEnrollQuestion() {
        return enrollQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_question
     *
     * @param enrollQuestion the value for i_enroll.enroll_question
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollQuestion(String enrollQuestion) {
        this.enrollQuestion = enrollQuestion == null ? null : enrollQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_phone
     *
     * @return the value of i_enroll.enroll_phone
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getEnrollPhone() {
        return enrollPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_phone
     *
     * @param enrollPhone the value for i_enroll.enroll_phone
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollPhone(String enrollPhone) {
        this.enrollPhone = enrollPhone == null ? null : enrollPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_name
     *
     * @return the value of i_enroll.enroll_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getEnrollName() {
        return enrollName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_name
     *
     * @param enrollName the value for i_enroll.enroll_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollName(String enrollName) {
        this.enrollName = enrollName == null ? null : enrollName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_company
     *
     * @return the value of i_enroll.enroll_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getEnrollCompany() {
        return enrollCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_company
     *
     * @param enrollCompany the value for i_enroll.enroll_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollCompany(String enrollCompany) {
        this.enrollCompany = enrollCompany == null ? null : enrollCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_position
     *
     * @return the value of i_enroll.enroll_position
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getEnrollPosition() {
        return enrollPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_position
     *
     * @param enrollPosition the value for i_enroll.enroll_position
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollPosition(String enrollPosition) {
        this.enrollPosition = enrollPosition == null ? null : enrollPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_email
     *
     * @return the value of i_enroll.enroll_email
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getEnrollEmail() {
        return enrollEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_email
     *
     * @param enrollEmail the value for i_enroll.enroll_email
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollEmail(String enrollEmail) {
        this.enrollEmail = enrollEmail == null ? null : enrollEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_money
     *
     * @return the value of i_enroll.enroll_money
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Double getEnrollMoney() {
        return enrollMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_money
     *
     * @param enrollMoney the value for i_enroll.enroll_money
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollMoney(Double enrollMoney) {
        this.enrollMoney = enrollMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_enroll.enroll_pay_state
     *
     * @return the value of i_enroll.enroll_pay_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Boolean getEnrollPayState() {
        return enrollPayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_enroll.enroll_pay_state
     *
     * @param enrollPayState the value for i_enroll.enroll_pay_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setEnrollPayState(Boolean enrollPayState) {
        this.enrollPayState = enrollPayState;
    }
}