package org.zucc.web.entity;

import java.io.Serializable;
import java.util.Date;

public class IExperience implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_experience.expId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long expid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_experience.exp_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long expUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_experience.exp_startDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date expStartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_experience.exp_endDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date expEnddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_experience.exp_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String expDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_experience
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_experience.expId
     *
     * @return the value of i_experience.expId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getExpid() {
        return expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_experience.expId
     *
     * @param expid the value for i_experience.expId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setExpid(Long expid) {
        this.expid = expid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_experience.exp_userId
     *
     * @return the value of i_experience.exp_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getExpUserid() {
        return expUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_experience.exp_userId
     *
     * @param expUserid the value for i_experience.exp_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setExpUserid(Long expUserid) {
        this.expUserid = expUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_experience.exp_startDate
     *
     * @return the value of i_experience.exp_startDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getExpStartdate() {
        return expStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_experience.exp_startDate
     *
     * @param expStartdate the value for i_experience.exp_startDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setExpStartdate(Date expStartdate) {
        this.expStartdate = expStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_experience.exp_endDate
     *
     * @return the value of i_experience.exp_endDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date getExpEnddate() {
        return expEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_experience.exp_endDate
     *
     * @param expEnddate the value for i_experience.exp_endDate
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setExpEnddate(Date expEnddate) {
        this.expEnddate = expEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_experience.exp_description
     *
     * @return the value of i_experience.exp_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getExpDescription() {
        return expDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_experience.exp_description
     *
     * @param expDescription the value for i_experience.exp_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setExpDescription(String expDescription) {
        this.expDescription = expDescription == null ? null : expDescription.trim();
    }
}