package org.zucc.web.entity;

import java.io.Serializable;

public class ITeacher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.tid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long tUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String tImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_typeId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long tTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_card_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String tCardImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_simple_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String tSimpleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String tDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_tags
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String tTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_certificateImage
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String tCertificateimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_tage
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Integer tTage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_real_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String tRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_contact
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String tContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher.t_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Boolean tState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.tid
     *
     * @return the value of i_teacher.tid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.tid
     *
     * @param tid the value for i_teacher.tid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_userId
     *
     * @return the value of i_teacher.t_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long gettUserid() {
        return tUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_userId
     *
     * @param tUserid the value for i_teacher.t_userId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settUserid(Long tUserid) {
        this.tUserid = tUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_image
     *
     * @return the value of i_teacher.t_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String gettImage() {
        return tImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_image
     *
     * @param tImage the value for i_teacher.t_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settImage(String tImage) {
        this.tImage = tImage == null ? null : tImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_typeId
     *
     * @return the value of i_teacher.t_typeId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long gettTypeid() {
        return tTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_typeId
     *
     * @param tTypeid the value for i_teacher.t_typeId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settTypeid(Long tTypeid) {
        this.tTypeid = tTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_card_image
     *
     * @return the value of i_teacher.t_card_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String gettCardImage() {
        return tCardImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_card_image
     *
     * @param tCardImage the value for i_teacher.t_card_image
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settCardImage(String tCardImage) {
        this.tCardImage = tCardImage == null ? null : tCardImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_simple_description
     *
     * @return the value of i_teacher.t_simple_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String gettSimpleDescription() {
        return tSimpleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_simple_description
     *
     * @param tSimpleDescription the value for i_teacher.t_simple_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settSimpleDescription(String tSimpleDescription) {
        this.tSimpleDescription = tSimpleDescription == null ? null : tSimpleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_description
     *
     * @return the value of i_teacher.t_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String gettDescription() {
        return tDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_description
     *
     * @param tDescription the value for i_teacher.t_description
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settDescription(String tDescription) {
        this.tDescription = tDescription == null ? null : tDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_tags
     *
     * @return the value of i_teacher.t_tags
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String gettTags() {
        return tTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_tags
     *
     * @param tTags the value for i_teacher.t_tags
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settTags(String tTags) {
        this.tTags = tTags == null ? null : tTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_certificateImage
     *
     * @return the value of i_teacher.t_certificateImage
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String gettCertificateimage() {
        return tCertificateimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_certificateImage
     *
     * @param tCertificateimage the value for i_teacher.t_certificateImage
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settCertificateimage(String tCertificateimage) {
        this.tCertificateimage = tCertificateimage == null ? null : tCertificateimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_tage
     *
     * @return the value of i_teacher.t_tage
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Integer gettTage() {
        return tTage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_tage
     *
     * @param tTage the value for i_teacher.t_tage
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settTage(Integer tTage) {
        this.tTage = tTage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_real_name
     *
     * @return the value of i_teacher.t_real_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String gettRealName() {
        return tRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_real_name
     *
     * @param tRealName the value for i_teacher.t_real_name
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settRealName(String tRealName) {
        this.tRealName = tRealName == null ? null : tRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_contact
     *
     * @return the value of i_teacher.t_contact
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String gettContact() {
        return tContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_contact
     *
     * @param tContact the value for i_teacher.t_contact
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settContact(String tContact) {
        this.tContact = tContact == null ? null : tContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher.t_state
     *
     * @return the value of i_teacher.t_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Boolean gettState() {
        return tState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher.t_state
     *
     * @param tState the value for i_teacher.t_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settState(Boolean tState) {
        this.tState = tState;
    }
}