package org.zucc.web.entity;

import java.io.Serializable;
import java.util.Date;

public class ITeacherAuthentication implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher_authentication.t_authentication_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long tAuthenticationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher_authentication.t_authentication_tid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long tAuthenticationTid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher_authentication.t_authentication_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Boolean tAuthenticationState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher_authentication.t_authentication_updateTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Date tAuthenticationUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher_authentication.t_authentication_adminId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long tAuthenticationAdminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher_authentication.t_authentication_id
     *
     * @return the value of i_teacher_authentication.t_authentication_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long gettAuthenticationId() {
        return tAuthenticationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher_authentication.t_authentication_id
     *
     * @param tAuthenticationId the value for i_teacher_authentication.t_authentication_id
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settAuthenticationId(Long tAuthenticationId) {
        this.tAuthenticationId = tAuthenticationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher_authentication.t_authentication_tid
     *
     * @return the value of i_teacher_authentication.t_authentication_tid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long gettAuthenticationTid() {
        return tAuthenticationTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher_authentication.t_authentication_tid
     *
     * @param tAuthenticationTid the value for i_teacher_authentication.t_authentication_tid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settAuthenticationTid(Long tAuthenticationTid) {
        this.tAuthenticationTid = tAuthenticationTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher_authentication.t_authentication_state
     *
     * @return the value of i_teacher_authentication.t_authentication_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Boolean gettAuthenticationState() {
        return tAuthenticationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher_authentication.t_authentication_state
     *
     * @param tAuthenticationState the value for i_teacher_authentication.t_authentication_state
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settAuthenticationState(Boolean tAuthenticationState) {
        this.tAuthenticationState = tAuthenticationState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher_authentication.t_authentication_updateTime
     *
     * @return the value of i_teacher_authentication.t_authentication_updateTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Date gettAuthenticationUpdatetime() {
        return tAuthenticationUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher_authentication.t_authentication_updateTime
     *
     * @param tAuthenticationUpdatetime the value for i_teacher_authentication.t_authentication_updateTime
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settAuthenticationUpdatetime(Date tAuthenticationUpdatetime) {
        this.tAuthenticationUpdatetime = tAuthenticationUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher_authentication.t_authentication_adminId
     *
     * @return the value of i_teacher_authentication.t_authentication_adminId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long gettAuthenticationAdminid() {
        return tAuthenticationAdminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher_authentication.t_authentication_adminId
     *
     * @param tAuthenticationAdminid the value for i_teacher_authentication.t_authentication_adminId
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void settAuthenticationAdminid(Long tAuthenticationAdminid) {
        this.tAuthenticationAdminid = tAuthenticationAdminid;
    }
}