package org.zucc.web.entity;

import java.io.Serializable;

public class ITeacherType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher_type.typeid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private Long typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_teacher_type.typename
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher_type.typeid
     *
     * @return the value of i_teacher_type.typeid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public Long getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher_type.typeid
     *
     * @param typeid the value for i_teacher_type.typeid
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setTypeid(Long typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_teacher_type.typename
     *
     * @return the value of i_teacher_type.typename
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_teacher_type.typename
     *
     * @param typename the value for i_teacher_type.typename
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }
}