package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IAccount;
import org.zucc.web.entity.IAccountExample;

public interface IAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IAccount> selectByExample(IAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IAccount selectByPrimaryKey(Long aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IAccount record, @Param("example") IAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IAccount record, @Param("example") IAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_account
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IAccount record);
}