package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IColletion;
import org.zucc.web.entity.IColletionExample;

public interface IColletionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IColletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IColletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long collectionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IColletion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IColletion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IColletion> selectByExample(IColletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IColletion selectByPrimaryKey(Long collectionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IColletion record, @Param("example") IColletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IColletion record, @Param("example") IColletionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IColletion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_colletion
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IColletion record);
}