package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IComment;
import org.zucc.web.entity.ICommentExample;

public interface ICommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ICommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ICommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IComment> selectByExample(ICommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IComment selectByPrimaryKey(Long commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IComment record, @Param("example") ICommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IComment record, @Param("example") ICommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_comment
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IComment record);
}