package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.ICompany;
import org.zucc.web.entity.ICompanyExample;

public interface ICompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ICompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ICompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(ICompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(ICompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<ICompany> selectByExample(ICompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    ICompany selectByPrimaryKey(Long companyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ICompany record, @Param("example") ICompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") ICompany record, @Param("example") ICompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(ICompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_company
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(ICompany record);
}