package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.ICourseType;
import org.zucc.web.entity.ICourseTypeExample;

public interface ICourseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ICourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ICourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long courseTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(ICourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(ICourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<ICourseType> selectByExample(ICourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    ICourseType selectByPrimaryKey(Long courseTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ICourseType record, @Param("example") ICourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") ICourseType record, @Param("example") ICourseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(ICourseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(ICourseType record);
}