package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.ICourseAuthentication;
import org.zucc.web.entity.ICourseAuthenticationExample;

public interface ICourseAuthenticationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ICourseAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ICourseAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long courseAuthenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(ICourseAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(ICourseAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<ICourseAuthentication> selectByExample(ICourseAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    ICourseAuthentication selectByPrimaryKey(Long courseAuthenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ICourseAuthentication record, @Param("example") ICourseAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") ICourseAuthentication record, @Param("example") ICourseAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(ICourseAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_course_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(ICourseAuthentication record);
}