package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.ICoupon;
import org.zucc.web.entity.ICouponExample;

public interface ICouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ICouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ICouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long couponid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(ICoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(ICoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<ICoupon> selectByExample(ICouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    ICoupon selectByPrimaryKey(Long couponid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ICoupon record, @Param("example") ICouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") ICoupon record, @Param("example") ICouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(ICoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_coupon
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(ICoupon record);
}