package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IEmployee;
import org.zucc.web.entity.IEmployeeExample;

public interface IEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IEmployee> selectByExample(IEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IEmployee selectByPrimaryKey(Long eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IEmployee record, @Param("example") IEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IEmployee record, @Param("example") IEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_employee
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IEmployee record);
}