package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IHr;
import org.zucc.web.entity.IHrExample;

public interface IHrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IHrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IHrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long hrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IHr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IHr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IHr> selectByExample(IHrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IHr selectByPrimaryKey(Long hrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IHr record, @Param("example") IHrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IHr record, @Param("example") IHrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IHr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_hr
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IHr record);
}