package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IProject;
import org.zucc.web.entity.IProjectExample;

public interface IProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IProject> selectByExample(IProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IProject selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IProject record, @Param("example") IProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IProject record, @Param("example") IProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_project
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IProject record);
}