package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IReward;
import org.zucc.web.entity.IRewardExample;

public interface IRewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IReward> selectByExample(IRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IReward selectByPrimaryKey(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IReward record, @Param("example") IRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IReward record, @Param("example") IRewardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_reward
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IReward record);
}