package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IShareDetail;
import org.zucc.web.entity.IShareDetailExample;

public interface IShareDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IShareDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IShareDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long shareDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IShareDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IShareDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IShareDetail> selectByExample(IShareDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IShareDetail selectByPrimaryKey(Long shareDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IShareDetail record, @Param("example") IShareDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IShareDetail record, @Param("example") IShareDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IShareDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_share_detail
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IShareDetail record);
}