package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.ITeacherType;
import org.zucc.web.entity.ITeacherTypeExample;

public interface ITeacherTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ITeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ITeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(ITeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(ITeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<ITeacherType> selectByExample(ITeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    ITeacherType selectByPrimaryKey(Long typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ITeacherType record, @Param("example") ITeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") ITeacherType record, @Param("example") ITeacherTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(ITeacherType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(ITeacherType record);
}