package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.ITeacherTag;
import org.zucc.web.entity.ITeacherTagExample;

public interface ITeacherTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ITeacherTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ITeacherTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long tagid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(ITeacherTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(ITeacherTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<ITeacherTag> selectByExample(ITeacherTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    ITeacherTag selectByPrimaryKey(Long tagid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ITeacherTag record, @Param("example") ITeacherTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") ITeacherTag record, @Param("example") ITeacherTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(ITeacherTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_tag
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(ITeacherTag record);
}