package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.ITeacherAuthentication;
import org.zucc.web.entity.ITeacherAuthenticationExample;

public interface ITeacherAuthenticationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ITeacherAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ITeacherAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long tAuthenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(ITeacherAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(ITeacherAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<ITeacherAuthentication> selectByExample(ITeacherAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    ITeacherAuthentication selectByPrimaryKey(Long tAuthenticationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ITeacherAuthentication record, @Param("example") ITeacherAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") ITeacherAuthentication record, @Param("example") ITeacherAuthenticationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(ITeacherAuthentication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher_authentication
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(ITeacherAuthentication record);
}