package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.ITeacher;
import org.zucc.web.entity.ITeacherExample;

public interface ITeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(ITeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(ITeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(ITeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(ITeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<ITeacher> selectByExample(ITeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    ITeacher selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") ITeacher record, @Param("example") ITeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") ITeacher record, @Param("example") ITeacherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(ITeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_teacher
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(ITeacher record);
}