package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IUserType;
import org.zucc.web.entity.IUserTypeExample;

public interface IUserTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IUserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IUserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long utId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IUserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IUserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IUserType> selectByExample(IUserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IUserType selectByPrimaryKey(Long utId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IUserType record, @Param("example") IUserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IUserType record, @Param("example") IUserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IUserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user_type
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IUserType record);
}