package org.zucc.web.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.zucc.web.entity.IUser;
import org.zucc.web.entity.IUserExample;

public interface IUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int countByExample(IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByExample(IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insert(IUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int insertSelective(IUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    List<IUser> selectByExample(IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    IUser selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExampleSelective(@Param("record") IUser record, @Param("example") IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByExample(@Param("record") IUser record, @Param("example") IUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKeySelective(IUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_user
     *
     * @mbggenerated Tue Nov 03 09:22:01 CST 2015
     */
    int updateByPrimaryKey(IUser record);
}